### ISSUE TITLE
Error message raises an error

### ISSUE THREAD

**Issue by gordalina** [gordalina/hush#7]
In https://github.com/gordalina/hush/blob/master/lib/hush/resolver.ex#L65 error may not be a string as seen below here, and it throws a message which makes it harder to understand what's happening

```
ERROR! Config provider Hush.ConfigProvider failed with:
** (Protocol.UndefinedError) protocol String.Chars not implemented for %HTTPoison.Error{id: nil, reason: :nxdomain} of type HTTPoison.Error (a struct). This protocol is implemen...
    (elixir 1.13.1) lib/string/chars.ex:3: String.Chars.impl_for!/1 
    (elixir 1.13.1) lib/string/chars.ex:22: String.Chars.to_string/1 
    lib/hush/resolver.ex:65: Hush.Resolver.value!/3 
    lib/hush/resolver.ex:30: Hush.Resolver.reducer/2 
    (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3 
    lib/hush/resolver.ex:50: Hush.Resolver.reducer/2 
    (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3 
    lib/hush.ex:25: Hush.resolve!/1 
```

**Comment by duntonr** [comment]
I might be running into this.

```console
$ PHX_SERVER=true _build/prod/rel/srv/bin/srv.bat start
ERROR! Config provider Hush.ConfigProvider failed with:
{** (RuntimeError) Could not resolve {:hush, Elixir.Hush.Provider.AwsSecretsManager, "/xxx/xxx/xxx/test"}: errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (hush 0.5.0) lib/hush/resolver.ex:64: Hush.Resolver.value!/3
    (hush 0.5.0) lib/hush/resolver.ex:30: Hush.Resolver.reducer/2
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (hush 0.5.0) lib/hush/resolver.ex:50: Hush.Resolver.reducer/2
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (hush 0.5.0) lib/hush/resolver.ex:38: Hush.Resolver.reducer/2
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (hush 0.5.0) lib/hush/resolver.ex:50: Hush.Resolver.reducer/2
```

Phoenix app using the AWSSecretsManager provider in release mode.
erlang 24
elixir 1.13.4
phoneix 1.16.11

If I use Hush outside a release, things work great.  If I switch to the `SystemEnvironment` provider and with a release, it also works.  It seems the combinations of being inside a release and using the AWS provider are causing this.  This ETS table error occurs if the config is in `prod.exs` or `runtime.exs`

`mix.exs`:
```
...
releases: [
        srv: [
          config_providers: [
            {Hush.ConfigProvider, nil}
          ],
...
```

config in `runtime.exs`
```
...
alias Hush.Provider.AwsSecretsManager

config :bla_app, bla_app.Mailer,
  adapter: Swoosh.Adapters.SparkPost,
  api_key: {:hush, AwsSecretsManager, "/xxx/xxx/xxx/test"}
...
```

any help tracking this down is greatly appreciated!

**Comment by gordalina** [comment]
@duntonr I received an email of a message you posted, but it seems it was deleted. Do you still have that issue?

**Comment by duntonr** [comment]
Thanks for following up.  That's what happened.  Root cause was user error!
